<template>
  <section class="page page__privacy page__info">
    <div class="container">
      <h1>Privacy Policy</h1>
      <p>9plus9 doing business as Dosable's Privacy Policy outlines the obligations of all users of the platform, including both vendors (contractors) and clients. This policy is a continuation of the Terms of Service, so it is important to read both documents together.</p>
      <p>Dosable shall not (a) be subject to any obligations of confidentiality regarding any User Generated Content except as specified in Dosable’s Privacy Policy, or as otherwise specifically agreed to or required by law; (b) be obligated to pay you or any third party any compensation for any User Generated Content; and (c) be required to respond to any of your submissions as User Generated Content.</p>
      <h3>Information Collection</h3>
      <p>Dosable collects certain personally identifiable information about you, including information that is reasonably capable of being associated with you (“<b>Information</b>”).</p>
      <p>When registering an account on our Dosable Platform, it is mandatory to provide your Contact Information and Financial Information. As a user, this includes your first and last name, email address, phone number, birth date, and photo ID, which are necessary for the creation and management of your Dosable account. These details enable seamless communication between you and your Clients through our Platform.</p>
      <p><u>Personal Health Information</u>: By creating an account with Dosable, you are establishing a direct customer relationship to utilize the Service. Throughout your use of the Service, you may furnish information to Dosable, such as your name, email, social media profiles, date of birth, phone number, address, and transactional details. We categorize this information as not constituting "protected health information" or "medical information."</p>
      <p>You may also share certain health or medical information protected by applicable laws with Dosable. Dosable is not identified as a "covered entity" under the Health Insurance Portability and Accountability Act of 1996, Public Law 104-191, and its related regulations and amendments ("HIPAA"). The Pharmacies, Medical Groups, and/or Providers associated with the Service may or may not be "covered entities" or "business associates" under HIPAA. However, in specific cases, Dosable might be deemed a "business associate" of a Pharmacy or Medical Group.</p>
      <p>HIPAA may not be applicable solely based on the involvement of health information, and it might not govern transactions and/or communications with Dosable, the Pharmacies, Medical Groups, and/or Providers of the Service. In instances where Dosable is regarded as a "business associate," it could be subject to specific HIPAA provisions regarding protected Health Information ("PHI") that you share with Dosable, the Pharmacies, Medical Groups, and/or Providers. Moreover, any medical and/or health information subject to protections under applicable state laws will be handled in compliance with those laws (collectively, "Protected Information"). However, information not qualifying as Protected Information under applicable laws may be utilized or disclosed as outlined in this Privacy Policy.</p>
      <p>The Pharmacies, Medical Groups, and/or Providers each maintain their own Privacy Policy notices outlining how they handle and disclose Protected Information. By using the Service, you acknowledge receipt and confirm that you have read, accepted, and adhere to the Privacy Policies of the Pharmacies, Medical Groups, and/or Providers, available on their respective websites.</p>
      <p>Furthermore, by accessing or using the Service, you recognize that if HIPAA applies to Dosable, the Pharmacies, Medical Groups, and/or Providers, any information submitted to Dosable, not intended solely for the provision of diagnosis and treatment, is not considered Protected Information. Such information will be subject only to our Privacy Policy and any applicable state laws governing the privacy and security of such information. To clarify, the information provided to Dosable for account creation, including your name, email, social media profiles, date of birth, phone number, address, and transactional details, is not deemed Protected Information.</p>
      <h3>Information Dosable Collects Automatically</h3>
      <p><b>Device Data</b>. This includes gathering data concerning the device or browser you utilize, the operating system of your device, your internet service provider, the regional and language settings of your device, and device identifiers like IP address. When you access and engage with the Dosable Platform, Dosable may automatically collect specific information through cookies or other technologies. This information encompasses details such as the type of computer or mobile device you use, the unique device ID of your mobile device, the IP address of your computer or mobile device, your operating system, the type(s) of internet browser(s) you use, and information about how you utilize the Dosable Platform (referred to as "Device Information").</p>
      <p><b>Cookies</b>. We use “cookies” and equivalent technologies to collect information through our Website. Cookies are small data files stored on your device that act as a unique tag to identify your browser. We also use analytics tracking software’s provided by Google - Firebase Analytics.</p>
      <p>Persistent cookies help with personalizing your experience, remembering your preferences, and supporting security features. Additionally, persistent cookies allow us to bring you advertising both on and off the Platform. Persistent cookies may remain on your device for extended periods of time, and generally may be controlled through your browser settings. We utilize persistent cookies that only Dosable can read and use, and access mobile device IDs to:</p>
      <ul>
        <li>save your login information for future logins to the Dosable Platform;</li>
        <li>assist in processing items during checkout;</li>
        <li>hold session information; and</li>
        <li>track user preferences.</li>
        <li>Session cookies make it easier for you to navigate our Website and expire when you close your browser. We utilize session ID cookies and similar technologies to:</li>
        <li>enable certain features of the Dosable Platform;</li>
        <li>better understand how you interact with the Websites/Apps and the Dosable Platform;</li>
        <li>monitor usage by our Users and web traffic routing on the Dosable Platform;</li>
        <li>track the number of entries in Dosable promotions, sweepstakes and contests; and</li>
        <li>identify visited areas of the Dosable Platform.</li>
      </ul>
      <h3>How We Use Your Information</h3>
      <p>The main objective of gathering your information is to enhance your experience while using the Services. We utilize your information to closely observe the most utilized features of the Services and identify areas that require improvement. This includes analyzing usage patterns and geographic locations to determine the optimal places to offer or concentrate our services, features, and resources.</p>
      <p>We also use information that we collect about you or that you provide us:</p>
      <ul>
        <li>To enable Service providers to provide services to Clients;</li>
        <li>To operate and make available our Platform. We use your data to connect you with other Users to enable the posting of, selection for, completion of, and payment for Service Requests, in order to fulfill our contracts with Users;</li>
        <li>For billing and fraud prevention, on the basis of our legitimate interests in ensuring a safe and secure environment in which Clients and Vendors can meet and conduct business, and in order to comply with our legal obligations;</li>
        <li>In order to further our legitimate interests and fulfill the significant public interest of ensuring the safety of our Users in both online and offline environments, preventing or uncovering unlawful activities, safeguarding the public from dishonesty, and upholding the integrity of the Dosable Platform where Vendors frequently engage with Clients and may have access to their residences, we will carry out identification, qualification, and skill checks. This includes conducting criminal background checks and verifying the right to work, as permitted by local law;</li>
        <li>To analyze Dosable Platform usage as necessary for our legitimate interest in improving the Dosable Platform to grow our business;</li>
        <li>We will get in touch with you and send you transactional information, administrative notices, marketing notifications, offers, and communications related to your use of the Dosable Platform. This may be done through email, SMS, push notifications, or other means. We will obtain your consent when necessary according to applicable law. Our purpose is to ensure effective communication and engagement with our Users and to promote our business, which aligns with our legitimate interests;</li>
        <li>To provide you with Client support in order to fulfill our contracts with Users;</li>
        <li>For internal market research for our legitimate interest in improving the Dosable Platform to grow our business;</li>
        <li>For troubleshooting problems for our legitimate interests in ensuring a safe and secure environment in which Users can meet;</li>
        <li>To assist Users in the resolution of complaints and disputes between them, as necessary for our legitimate interests in facilitating good relations among Users;</li>
        <li>To enforce our Terms of Service and our legitimate interests in ensuring our Agreement is complied with; and</li>
        <li>As otherwise set forth in the Agreement, to show users’ profiles to one another.</li>
        <li>To improve the User Experience.</li>
        <li>To provide, develop and improve Dosable and its services, including making assessments and recommendations about the Service.</li>
        <li>To notify about changes of our Website or any services that we offer or provide though it.</li>
        <li>To allow you to participate in interactive features on our Website.</li>
        <li>For any other purpose with your consent.</li>
      </ul>
      <p>We also collect Users Personal Information for administrative purposes, such as addressing account and troubleshooting Website issues, investigating abuse on the Website, responding to User inquiries and enforcing and applying our Terms and Conditions of Service.</p>
      <p>Dosable uses IP addresses for systems administration purposes. We do not link IP addresses to any information that is personally identifiable.</p>
      <p>However, we may also release Personal Information or other information we collect, if we believe that such action is necessary to: (I) comply with legal requirements and processes; (II) identify, contact or bring legal action against persons or entities who are or we believe have caused or might cause injury to us or a third party; (III) defend or respond to claims brought or threatened against us, our employees, service providers, users of our Services or others;  (IV) vendors, service providers, and technicians who help with some of our processing and storage, including helping to answer your questions; and/or (V) otherwise to protect, assert rights, interests of Dosable and of our employees, service providers, Users of the Services or others. Any such release decisions may be made by us in our sole discretion.</p>
      <p>Although we aim to choose our third-party collaborators carefully, we cannot be held accountable for how they utilize your personal information.</p>
      <p>Furthermore, considering that Client information present on our Website holds value as a business asset, if we undergo reorganization, sale, or merger with another company, we reserve the right to sell, assign, or transfer your personal information to the buyer of our business assets, or to a relevant affiliate, as applicable.</p>
      <h3>Information sharing</h3>
      <p>To grant you access to the Services, certain third parties engaged by Dosable to perform various services, such as hosting, analytical tasks, data management, or similar functions, or those acting on our behalf ("Service Providers"), may have access to your personal information, including your Health Information. These Service Providers are authorized to utilize your information solely for the designated service and are prohibited from sharing it with any third parties. They are obligated to adhere to the terms outlined in our Privacy Policy, which includes implementing reasonable measures to ensure the security of your personal information. Periodically, we may engage trusted third-party providers who receive your personal information or Health Information to conduct anonymized aggregate analyses of the data. Our contractual agreements mandate that these partners maintain sufficient security measures for the provided personal information. We strictly prohibit such third parties from selling your personal information to other entities.</p>
      <p><b>Third-Party Platforms</b>: Dosable connects with various third-party devices and services, such as Stripe, to ensure the best service for you. The website might contain links to other websites that are not maintained by us, and we want to clarify that Dosable is not responsible for the privacy policies or practices of these third parties or their websites. This includes any apps linked to or linking from our website. If you disclose personally identifiable information to these third parties, they may have different rules regarding its use and disclosure. We strongly advise you to review the privacy policies of these websites before sharing your personal information with them. By linking to third-party websites, you may be subject to their terms and conditions as well as other policies. Dosable cannot guarantee the accuracy or authenticity of the information found on these third-party websites, and any link you establish with another website is done at your own risk. Dosable holds no liability in such cases.</p>
      <h3>Opting Out or Unsubscribe.</h3>
      <p>In order to provide you with our daily, weekly, or monthly newsletter service, we gather your name and email address. The email address you provide will be utilized to deliver the information you have requested from this website.</p>
      <p>The data we gather is solely utilized to fulfill the requested services, and we do not disclose it to any other entities for business motives. Under no circumstances will we sell or lease your email address.</p>
      <p>To unsubscribe from our e-mails or other communications from us, you may follow the "unsubscribe" link at the bottom of the e-mail or sign onto your account and change settings. However, this section does not cover the messages and advertisements you may receive from the Website.</p>
      <h3>How Long Is This Data Stored For?</h3>
      <p>Your data will be stored as long as you have an active account with us. Please be aware that if you decide to close your account, your data will not be immediately deleted. If you wish to have your data deleted immediately, you can send us an email requesting so.</p>
      <h3>Security</h3>
      <p>We take the security of your data very seriously, but no data transmission or storage is 100% secure. This means that there is always a risk that your information could be stolen, destroyed, or inadvertently disclosed. While we take steps to protect your information, we cannot guarantee its absolute security.</p>
      <p>The safety and security of your information also depend on you. Where we have given you (or where you have chosen) a password for access to certain parts of our Website, you are responsible for keeping this password confidential. We advise you not to share your password with anyone.</p>
      <h3>User Data Rights</h3>
      <p>By using our Services and participating in Marketing Activities, you expressly give consent for the collection and use of your personal information as outlined in this Privacy Policy. This consent does not hinder the lawful processing allowed by other legal bases, such as fulfilling contractual obligations, complying with applicable laws, and pursuing legitimate purposes.</p>
      <h3>Child protection</h3>
      <p>Our Services are designed and aimed at individuals who are not children. Individuals under the age of 18 are not permitted to utilize our Services. By using our Services, you affirm that you are at least 18 years old and acknowledge that you must be at least 18 years old to create an account and make purchases for the Services featured on our platform. We do not intentionally collect or retain Personal Information from individuals under the age of 18. If we become aware that we have unintentionally obtained Personal Information from individuals under the age of 18, we will take appropriate steps to delete or eliminate such information from our records.</p>
      <h3>Your Rights Under The General Data Protection Regulations</h3>
      <p>If you are part of the EU, you possess the subsequent entitlements:</p>
      <p>Request More Information. If you desire to gain further knowledge or have any reason to do so, you have the option to request additional information regarding the data we gather. Likewise, if you intend to lodge a complaint, you may also express your wish.</p>
      <p>Access Any Data We’ve Collected. You have the option to ask for a detailed disclosure of the personally identifiable data we have gathered.</p>
      <p>Update Any Data We’ve Collected. You have the option to ask for the rectification, modification, or updating of any or all of the personally identifiable information we have gathered.</p>
      <p>Delete Any or All Data We’ve Collected. You have the option to ask for the deletion and removal of any or all of the personally identifiable information we have gathered, ensuring it is no longer retained in our records.</p>
      <p>You have the option to revoke your consent for the collection and utilization of your data. At any given moment, you are free to withdraw your consent regarding the gathering of your data</p>
      <p>In order to exercise any of these rights, simply contact us.</p>
      <h3>Right to Access or Correct Personal Information</h3>
      <p>You are entitled to access and rectify your personal information. If you wish to review or make corrections to your personal information, you can visit your account profile page or send us an email using the contact information provided in the support@dosable.com</p>
      <p>Once we receive your written request, we will provide you with a copy of your Personal Information. However, in certain exceptional cases, we may be unable to disclose all relevant information if it pertains to another user. If this situation arises, we will provide you with an explanation upon request. We strive to address all requests for access and modifications promptly. We will make reasonable efforts to ensure the accuracy and currency of your Personal Information and offer you options to update, correct, delete, or add to it as necessary. Any amended Personal Information will be shared with authorized parties, as permitted by our disclosure policies.</p>
      <h3>Notice to EU Residents as per GDPR Regulations</h3>
      <p><u>Personal information</u> With respect to EU data subjects, the term "personal information" as used in this Privacy Policy is equivalent to "personal data" as defined in the European Union General Data Protection Regulation (GDPR).</p>
      <p><u>Processing Purposes</u> To communicate with you to optimize our platform for compliance fraud prevention and to provide our Service.</p>
      <p><u>Sensitive Data</u> Some of the information you provide us may constitute sensitive data as defined in the GDPR (also referred to as special categories of personal data), including identification of your race or ethnicity on government-issued identification documents.</p>
      <p><u>Legal Bases for Processing</u> Your personal information is utilized in accordance with the law. It is necessary for us to inform you about the legal grounds on which we process your personal data, as outlined below. Should you have any inquiries regarding the legal bases for processing your personal information, please reach out to us at support@dosable.com.</p>
      <p><u>Legal Basis</u> Our legitimate interests encompass these processing activities. Before proceeding with the processing of your personal information for these interests, we make an effort to evaluate and balance the potential effects on you, both positive and negative, as well as your rights. We refrain from utilizing your personal information for activities that would negatively outweigh our interests, unless we have obtained your consent or are legally obligated or permitted to do so.</p>
      <p>If we rely on your consent as the basis for using your personal information, you retain the right to withdraw it at any time. You can do this by following the instructions provided in the Service or by reaching out to us at support@dosable.com.</p>
      <p><u>Your Rights</u> Under the GDPR, you have certain rights regarding your personal information. You may ask us to take the following actions about the personal information that we hold:</p>
      <ul>
        <li>Opt-out: Stop sending you direct marketing communications which you have previously consented to receive. We may continue to send you Service-related and other non-marketing communications.</li>
        <li>Access: Provide you with information about our processing of your personal information and give you access to your personal information.</li>
        <li>Correct</li>
        <li>Update or correct inaccuracies in your personal information.</li>
        <li>Delete</li>
        <li>Delete your personal information.</li>
        <li>Transfer</li>
        <li>Restrict</li>
        <li>Object</li>
        <li>Object to our reliance on our legitimate interests as the basis of our processing of your personal information that impacts your rights.</li>
        <li>
          Data Subject Access Rights Requests <br><br>
          In order to verify your identity and handle your request effectively, we might ask you for certain details. Depending on the relevant laws, there may be instances where we are obligated or allowed to reject your request. If your request is declined, we will provide an explanation within the limits imposed by the law. If you wish to file a complaint about the usage of your personal information or address any concerns regarding your personal information, please feel free to reach out to us at support@dosable.com.
        </li>
        <li>Use for New Purposes: In situations where it is legally allowed and aligns with the original purpose of collecting your personal information, we might utilize it for purposes not explicitly mentioned in this Privacy Policy. If there arises a need to use your personal information for an unrelated purpose, we will inform you and clarify the legal justification for such usage. In cases where we have relied on your consent for a specific use of your personal information, we will seek your consent again for any unrelated purpose. If you object to such usage, you will have the option to discontinue using the Service.</li>
      </ul>
      <p><u>Data Retention</u> Your Personal Data is stored securely during the entire duration of your account with us. We will keep your Personal Data only for the duration required to fulfill the purposes for which it was collected, such as meeting legal, accounting, or reporting obligations, or resolving disputes. The factors we consider when deciding how long to retain your data include the current contractual agreements, legal and statutory limitation periods, relevant regulatory requirements, and industry standards..</p>
      <p>The duration for which we retain your personal data varies depending on the jurisdiction. However, we provide details below regarding our typical retention periods for different categories of your personal data.</p>
      <p>Records of our communications with you (e.g., support tickets opened via email or Twitter) may be kept indefinitely.</p>
      <p>Contact information used for marketing purposes is retained until you decide to unsubscribe. After that, your details will be added to our suppression list indefinitely. Email information collected from Accessibility Users will never be utilized for marketing purposes.</p>
      <p>Information collected through technical means such as cookies, webpage counters, and other analytics tools is discarded as soon as possible. However, it may be kept for a limited period of up to one year from the expiration of the cookie. This is typically done in a de-identified and aggregated form, unless we detect potential abuse of our Service. In such cases, we will retain the information to help us prevent future abuse. Please note that this anonymized and aggregated information cannot be linked to you, your household, an IP address, or any personal information stored.</p>
      <p><u>Changes to this Privacy Policy</u> Any information that we collect is subject to the Privacy Policy in effect at the time such information is collected. We may, however, revise the Privacy Policy from time to time. If a revision is material, as determined solely by us, we will try to notify you, for example, via e-mail. The current version will always be posted to our Privacy Policy page.</p>
      <p>If you have any questions about this Privacy Policy, please contact us at support@dosable.com</p>
      <p><b>Notice to California Residents as per CCPA guidelines</b></p>
      <p>In this section, we provide further details regarding the personal information we gather about individuals residing in California, as well as the rights granted to them under the California Consumer Privacy Act, commonly known as the CCPA.</p>
      <p>As per California Civil Code Section 1789.3, users in California have specific entitlements related to consumer rights, and we want to make sure they are aware of them. California residents have the option to contact the Complaint Assistance Unit of the Division of Consumer Services, which is part of the California Department of Consumer Affairs.</p>
      <p>If you are a California consumer and wish to exercise your rights under the CCPA, you can get in touch with us at support@dosable.com. It is important to note that in order for us to proceed with your request, you must first verify your identity by providing your government identification. In compliance with California law, you are also allowed to designate an authorized agent to make a request on your behalf. To do so, you must supply a valid power of attorney, as well as valid government-issued identification for both the requester and the authorized agent.</p>
      <p>To learn about the specific categories of personal information we have collected from you, please refer to the "Information We Collect" section mentioned earlier. The purpose of collecting this information aligns with the business and commercial objectives outlined in the "How We Use Personal Information" section.</p>
      <p>Please be aware that upon request, we may share information related to fraud risk associated with an individual IP address with an Integrator.</p>
      <p>We want to assure you that the Company does not engage in the "selling" of personal information, as defined by the CCPA. For more details on the types of third-party cookies, if any, utilized by us, kindly consult the "Third-Party Analytics and Tracking Technologies" section mentioned earlier.</p>
      <p>The CCPA grants California consumers certain privileges, within certain constraints. These privileges include the ability to inquire about specific categories or individual elements of their personal information that we gather (including its usage and disclosure), to have their personal information erased, to decline participation in any potential "sales," and to be free from discrimination as a result of exercising these rights.</p>
    </div>
  </section>
</template>