<template>
  <section class="page page__terms page__info">
    <div class="container">
      <h1>Terms of Service</h1>
      <p>By using some of the Services through the Website, You expressly consent to be bound by these terms and all legislation which regulate the Website together with Services. The terms form a contract that is legally binding to both you and 9plus9, LLC  operating as Dosable with regard to your utilization of the Website and/ or the Services and apply to all the users of this solution, whether signed up or on the Website.</p>
      <p>As used in this Agreement, “www.dosable.com", "we," "us,", "Website", and "our" shall mean Dosable and its subsidiaries and affiliates. By utilizing the services available through our site (the "Services"), you accept to be bound by these terms regarding the Services provided. These terms do not alter in any real manner the terms of any other agreement you may have with Dosable. That you will be authorized to do this if you are using the Services with respect to any entity, you represent.</p>
      <p>We may, at our sole discretion, modify or revise these Terms of Service, policies and price of services by giving notice on our Website and/or through the Services, and you agree to be bound by such modifications or revisions. Although Dosable may attempt to notify you, when major changes are made to these Terms of Service, you should periodically click on our Terms of Service to review any updates. All changes shall be effective immediately when we post them and shall apply to all access to and use of our Website thereafter. Nothing in these Terms of Service shall be deemed to confer any third-party rights or benefits hereunder.</p>
      <p>BY USING THE SITE, YOU ARE ACCEPTING AND AGREEING TO THESE TERMS OF SERVICE. YOU REPRESENT THAT YOU ARE OF SUFFICIENT LEGAL AGE IN YOUR JURISDICTION OR RESIDENCE TO ENTER INTO THIS AGREEMENT. IF YOU DO NOT AGREE WITH ANY OF THE PROVISIONS OF THESE TERMS & CONDITIONS, YOU SHOULD DISCONNECT DOSABLE AND CEASE USING IT.</p>
      <p><b>Applicable Laws</b> shall mean and include all applicable statutes, enactments, acts of the legislature or parliament, provincial laws, ordinances, rules, by-laws, regulations, notifications, guidelines, policies, directions, directives and orders of any governmental authority, tribunal, or a court of United States of America.</p>
      <p><b>You/Customer means</b> a person who is using Dosable services and/or completes the Dosable account registration process and a Physician who is providing services on the Dosable platform.</p>
      <p><b>Partner</b> means the person or entity providing products and services via a Website.</p>
      <p><b>Products</b> mean the items, medicines, ointments, and other goods and services supplied by our Partners such as pharmacies, have agreed to supply to the Customers via the website.</p>
      <p><b>Content</b> means reports, text, documents, graphics, images, software, audio, video, information or other materials.</p>
      <p><b>Users Content</b> means information and content provided by you and incorporated in Service listings, chats, e-mails, posts, and feedbacks.</p>
      <p><b>Representative</b> means an entity and its Affiliate(s), any director, officer, employee, consultant, contractor, agent, distributors and attorney associated with the Company.</p>
      <p><b>Site or Sites</b> means www.dosable.com</p>
      <h3>Ambit of Service</h3>
      <p>Dosable operates as a technological platform connecting registered users of the Website with Physicians, pharmacies, and other healthcare providers for medical consultations and the dispensing of prescribed medications. It is important to clarify that Dosable is not a healthcare provider or pharmacy, and it does not offer or provide medical advice, treatment recommendations, or pharmacy services. By using the platform, you acknowledge that you are not establishing a physician-patient relationship with Dosable. Dosable is not responsible for any advice, medical care, or treatment provided by affiliated Physicians, pharmacies ("Pharmacies"), or other healthcare providers. Additionally, Dosable disclaims liability for any consequences, injuries, or harm resulting from such interactions.</p>
      <p>Dosable does not own the Medical Practice, nor does it control the practice of medicine by the Medical Practice or its Physicians. The content on the Website and Services, including text, audio, video, photographs, illustrations, graphics, and visuals, is for informational purposes only and does not constitute professional medical advice, diagnosis, treatment, or recommendations from Dosable.</p>
      <p>Dosable offers products and services to registered Service users ("Users"), including those provided by Dosable itself or third-party medical providers, pharmacies, and vendors affiliated with the Company's Service. The Service provides access to prescription fulfillment services from specific pharmacies, such as EHT Pharmacy LLC doing business as Curexa and Madame Rx LLC doing business as Chemistry Rx (referred to as the "Pharmacies"). Additionally, users may have access to medical groups on the Platform (referred to as the "Medical Groups"), such as Beluga Health . These Medical Groups employ or contract with healthcare professionals, also known as "Providers" or "Health Counselors," who offer various healthcare services through the Platform. By accepting the Agreement, you acknowledge and agree that any services received from the Pharmacies, Medical Groups, and/or Providers through the Platform are governed by this Agreement, with the Pharmacies, Medical Groups, and Providers recognized as third-party beneficiaries.</p>
      <p>While you do not form a doctor-patient or any other health care provider-patient relationship with Dosable, your use of the Service establishes a direct customer relationship with Dosable. This includes engaging in the purchase of prescription and/or non-prescription products, as well as non-medical services directly offered to you by Dosable through the Service. As part of this customer relationship, you may provide the Company with personal information, including health information, either directly or on your behalf. The usage of such information by the Company is governed by its Privacy Policy, which can be found in the "Privacy Policy" section on the Company's Website.</p>
      <h3>Account Creation</h3>
      <p>Upon completing your registration, you can utilize the website to seek consultation for prescription filling at a different pharmacy. We will forward the prescription to your chosen physician and, if deemed medically necessary, process your order for products. Some items on the website may require a prescription, while others do not. A licensed physician from the relevant medical practice in your state will be assigned to review your registration, provide a diagnosis, assess the medical appropriateness of your desired products, and, if suitable, issue a prescription. However, the issuance of any prescription is not guaranteed. You have the option to request a different physician. Your product order will only be accepted after a physician conducts a medical consultation, evaluates the clinical appropriateness of the requested item, and issues a prescription if required. DEA controlled substances will not be prescribed. If your physician decides not to issue a required prescription after a medical consultation,. If you opt for a different pharmacy, you are responsible for picking up and paying for the prescription. Some products on the website may not necessitate a prescription, allowing you to purchase them post-registration without a medical consultation. Prescriptions filled by the pharmacy will be shipped to you, with associated shipping costs.. Pharmaceutical product returns cannot be accepted. Dosable does not endorse specific medications, pharmacies, or physicians.</p>
      <h3>Health Counseling</h3>
      <p>Users acknowledge and accept that Dosable bears no responsibility for the information conveyed by any Health Counselors. Dosable does not offer any medical services. In addition to other functions, Dosable furnishes a technological platform to facilitate coordination and communication with healthcare providers. It is understood that engaging in coordination and/or consultation with a healthcare provider via the Dosable platform does not establish a provider-patient relationship with Dosable or its Health Counselors, as defined by US federal and state laws.</p>
      <p>Whenever Dosable employs terms such as "your physician," "your medical practitioner," "your doctor," "healthcare provider," or similar expressions, including in this Agreement, the Company is specifically addressing your primary care physician. This refers to the healthcare professional with whom you have a mutually recognized doctor-patient relationship within the state of your residence. It's important to note that Health Counselors on the Dosable platform are not considered "your" doctor, physician, medical practitioner, healthcare provider, or dermatologist. Consultations with the doctors affiliated with the Company do not serve as a substitute for your existing relationship with any physician.</p>
      <p>Telemedicine Provider License Disclosure</p>
      <p>It is important to note that in compliance with the telehealth laws of specific states, we are required to publicly disclose licensure and identifying information about our provider, Jonah Mink, MD, from Beluga Health, whose National Provider Identifier (NPI) is 1083052351. This disclosure is in accordance with the regulations of California (Cal. Bus. & Prof. Code § 680.5(e)), Massachusetts (Mass. Board of Registration in Medicine Policy 15-05 (2015) (p.7)), Rhode Island (R.I. Board of Medical Licensure and Discipline Telemedicine Guidelines), and Vermont (Vt. Board of Medical Practice Policy on Telemedicine).</p>
      <p>By using Dosable's services, you acknowledge and agree to the public disclosure of the mentioned licensure information during your interactions with our telemedicine provider, Jonah Mink, MD.</p>
      <h3>Shipping</h3>
      <p>Dosable does not currently offer international shipping and reserves the right to decline orders with delivery addresses outside of the USA. Shipping is available within the USA. Your initial order will only be processed and shipped once you've submitted your Government-issued ID. Monthly subscriptions are dispatched every twenty-five (25) days to ensure timely delivery of your monthly product supply. To prevent processing of your next order, ensure your subscription is paused at least three (3) days before the next billing date.</p>
      <p>Unless specified otherwise on the Website and/or Service during purchase, Dosable may add applicable shipping and handling fees to your order. Shipping fees are also levied on the products purchased via subscription. Upon shipment, you'll receive an email containing a tracking number. While Dosable may provide estimated delivery timeframes, these are subject to change. Dosable bears no responsibility for delays caused by third-party carriers or other delivery services beyond its control. Once your order is handed over to a third-party carrier, you assume responsibility for any delivery issues. Dosable is not accountable for incorrect delivery addresses entered by the customer or a third party acting on behalf of the customer. It is essential to double-check and accurately input your delivery address during checkout. Any alterations to your delivery address must be made at least three (3) days before your next billing date.</p>
      <h3>Returns & Refunds</h3>
      <p>Should you be unsatisfied with your Dosable product or service for any reason, kindly reach out to us at support@dosable.com. Based on the situation, we may, at our sole discretion, either replace the ordered products or issue a full or partial refund of the purchase price. Prior to granting a refund, replacement, or credit, we may request that you, at your own cost, return the product and/or provide photographic documentation elucidating the grounds for your dissatisfaction. Refunds will be credited to the payment method used for the initial order.</p>
      <p>It is your responsibility to inspect all products for damage or other issues upon delivery. Please contact Dosable at support@dosable.com within 7 days of receiving the product to allow us to investigate and replace any damaged items.</p>
      <p>Returns for any non-pharmaceutical must be initiated within 30 days from the date of your order delivery. Refunds are limited to the amount paid for the product of that month. You are accountable for shipping the unused portions of the product in its original packaging back to Dosable, and you are also responsible for the associated shipping and handling costs of the return</p>
      <h3>Reliance on Information Posted</h3>
      <p>Kindly note that, unless expressly stated or otherwise mandated by applicable law, Dosable does not authenticate the accuracy of information presented on the Services by third parties. Details concerning prescription medications available for purchase on the website are directly supplied by our affiliated pharmacies and have not undergone review or approval by Dosable. Your reliance or use of any information acquired through the Services is undertaken at your own risk.</p>
      <p>This Website and services listed on the Website may contain typographical errors or inaccuracies and may not be complete or current. Available information on the Website is solely for general information purposes. We disclaim all liability and responsibility arising from any reliance placed on such materials by you or any other visitor to the Website or by anyone who may be informed of any of its contents. Any reliance you place on such information is strictly at your own responsibility and risk.</p>
      <h3>Third-Party Links, Content, And Services</h3>
      <p>Dosable Services rely on, or interoperate with, third-party products and services. The Website and Content available through the Website may integrate with other third-party platforms and websites such as third-party pharmacies, payment processor Services, e.g. Stripe, PayPal, Payoneer etc. and third-party helpdesks. If you link to Third Party Websites, you may be subjected to those Third-Party Websites' Terms of Service and other policies. Dosable makes no representation or guarantee as to the accuracy or authenticity of the information contained in any of such Third-Party Website, data protection and your linking to any other Website is completely at your own risk, and Dosable disclaims all liability thereto.</p>
      <p>These third-party products and services are beyond Dosable's control, but their operation may impact or be impacted by Dosable Services' use and reliability. You acknowledge and agree that: (i) the use and availability of the Services is dependent on third party product vendors and service providers, (ii) these third-party products and services may not operate in a reliable manner 100% of the time, and they may impact the way that Dosable Services operate, and (iii) Dosable is not responsible for damages and losses due to the operation of these third-party products and services.</p>
      <h3>Ownership and Intellectual Property</h3>
      <p>The Website and all worldwide copyrights, trade secrets, and other intellectual property rights therein are the exclusive property of Dosable and its licensors. Dosable and its licensors reserve all rights in and to the Website not expressly granted to you herein. There are no implied licenses herein. All suggestions or feedback provided by you to Dosable with respect to the Website shall be Dosable' property. Dosable may use, copy, modify, publish, or redistribute the submission and its contents for any purpose and in any way without any compensation to you.</p>
      <p>This Website, our Product, and all other Content forming part of the Website, including without limitation, all photographs, ideas, images, designs, information, interfaces, text, graphics, brand names, logos and trademarks, are protected by copyright, trademark and other intellectual property laws of United States of America.</p>
      <p>You acknowledge and agree that Dosable owns, controls or is licensed all legal right, title and interest in and related to the Product and Website, including all intellectual property rights. You may not:</p>
      <ul>
        <li>modify or copy the idea of trade, layout, or appearance of the Product and Website or any computer software or code contained in the Website; and/or</li>
        <li>decompile or disassemble, reverse engineer or otherwise attempt to discover or access any source code related to the Website.</li>
      </ul>
      <p>If you believe that anything on or available through the Services infringes upon any copyright which you own or control, you may contact us at support@dosable.com</p>
      <p>You acknowledge that all intellectual property rights, including without limitation, copyrights, patents, trademarks, and trade secrets, in the Product, and Services (i.e., the Websites, and Mobile version of the Websites) are owned by Dosable or its affiliates or our licensors. Your possession, access, and use of the Product, and Services do not transfer to you or any third party any rights, title, or interest in or to such intellectual property rights. Dosable and its affiliates and licensors and suppliers reserve all rights not granted in these Terms. The Services are licensed to you, not sold, under these Terms.</p>
      <p>You may not use the Content of the Services in any other public or commercial manner, nor may you copy or incorporate any of the Content of the Services into any other work, including your own Website, without the written consent of Dosable.</p>
      <h3>Digital Millennium Copyright Act (DMCA) Notice and Policy</h3>
      <h4>Notifications</h4>
      <p>We respect the intellectual property rights of others. If you believe that any material available on or through the Site infringes upon any copyright you own or control, please immediately notify ("Notification") our Designated Copyright Agent using the contact information provided below. You agree to contact us first and provide such notification before approaching any third-party. Please be advised that pursuant to federal law you may be held liable for damages if you make material misrepresentations in a Notification. Thus, if you are not sure that material located on or linked to by the Site infringes your copyright, you should consider first contacting an attorney. If you believe that any material available on or through the Site infringes upon any copyright you own or control, please immediately notify our designated copyright agent at:</p>
      <p>Dosable 9plus9, LLC <br>Attn: Copyright Agent <br>E-mail: support@dosable.com</p>
      <p>All Notifications should meet the requirements of DMCA 17 U.S.C. § 512(c)(3) and include the following information: (1) A physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed; (2) identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works on the Site are covered by the Notification, a representative list of such works on the Site; (3) identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled, and information reasonably sufficient to permit us to locate the material; (4) information reasonably sufficient to permit us to contact the complaining party, such as an address, telephone number, and, if available, an e-mail address at which the complaining party may be contacted; (5) a statement that the complaining party has a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and (6) a statement that the information in the notification is accurate, and under penalty of perjury, that the complaining party is authorized to act on behalf of the owner of an exclusive right that is allegedly infringed upon.</p>
      <h3>Limitation of Liability</h3>
      <p>You agree that in no event, Dosable or any of its officers, the medical practice, the physicians, and the pharmacies shall employees, agents are responsible or accountable for any of your listing, postings, or information and nor shall they be liable for any misuse, illegal activity, or third-party content as most postings, listings or information are generated by various users directly.</p>
      <p>You understand and agree that we do not guarantee the accuracy or legitimacy of any listing, posting, or information provided by other users or sources including but not limited to Links/Hyperlinks and quoted content. You further agree that we are not liable for any loss of money, goodwill, or reputation, or any special, indirect, or consequential damages arising out of your use of the Website or as a result of any sale, purchase of goods and services with other users of the Website. Dosable makes no representations about, and does not guarantee the quality, safety, or legality of, the Vendor Services. We also cannot guarantee continuous or secure access to our Services. Accordingly, to the extent legally permitted, we exclude all implied warranties of merchantability, fitness, or quality of the Website and our services.</p>
      <p>IN NO EVENT SHALL DOSABLE, ITS OFFICERS, DIRECTORS, EMPLOYEES, OR AGENTS, BE LIABLE TO YOU FOR ANY  DIRECT, INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE, OR CONSEQUENTIAL DAMAGES WHATSOEVER RESULTING FROM ANY (I) ERRORS, MISTAKES, OR INACCURACIES OF CONTENT DISPLAYED ON THE DEVICE, (II) PERSONAL INJURY OR PROPERTY DAMAGE (INCLUDING YOUR SMARTPHONE), OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO AND USE OF OUR SERVICES, (III) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN, (IV) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM OUR SERVICES, (V) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE, WHICH MAY BE TRANSMITTED TO OR THROUGH OUR SERVICES BY ANY THIRD PARTY, AND/OR (VI) ANY ERRORS OR OMISSIONS IN ANY CONTENT OR FOR ANY LOSS OR DAMAGE OF ANY KIND, IN EACH CASE WHETHER BASED ON WARRANTY, CONTRACT, TORT, OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT DOSABLE IS ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. YOU SPECIFICALLY ACKNOWLEDGE THAT DOSABLE SHALL NOT BE LIABLE FOR CONTENT OR THE DEFAMATORY, OFFENSIVE, OR ILLEGAL CONDUCT OF ANY THIRD PARTY AND THAT THE RISK OF HARM OR DAMAGE FROM THE FOREGOING RESTS ENTIRELY WITH YOU.</p>
      <p>DOSABLE AND OUR LICENSORS AND SUPPLIERS MAKE NO WARRANTY THAT DEFECTS WILL BE CORRECTED OR THAT THE SERVICES: (I) WILL MEET YOUR REQUIREMENTS; (II) WILL BE COMPATIBLE WITH YOUR HOME NETWORK, COMPUTER OR MOBILE DEVICE; (III) WILL BE AVAILABLE ON AN UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE BASIS; OR (IV) WILL BE ACCURATE OR RELIABLE. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM DOSABLE OR THROUGH THE SERVICES SHALL CREATE ANY WARRANTY.</p>
      <p>YOU UNDERSTAND AND AGREE THAT THIS LIMITATION OF LIABILITY SHALL APPLY EVEN IF DOSABLE IS FOUND LIABLE FOR ANY LOSS OR DAMAGE DUE TO BREACH OF CONTRACT, BREACH OF EXPRESS OR IMPLIED OR LIMITED WARRANTY, NEGLIGENCE OF ANY KIND OR DEGREE, STRICT PRODUCT LIABILITY, SUBROGATION, INDEMNIFICATION OR CONTRIBUTION, OR ANY OTHER THEORY OF LIABILITY. HOWEVER, THIS LIMITATION OF LIABILITY SHALL NOT APPLY TO ANY WILLFUL, WANTON, INTENTIONAL OR RECKLESS MISCONDUCT OF DOSABLE OR GROSS NEGLIGENCE OF DOSABLE IN THOSE STATES THAT DO NOT PERMIT LIMITATION OF LIABILITY FOR GROSS NEGLIGENCE.</p>
      <h3>Non-Disclosure of Confidential information</h3>
      <p>“Confidential Information” shall mean non-public, proprietary information revealed by Dosable or Vendor of an applicable project listing (whether in writing, orally or by any other means) including, but not limited to, (a) information expressly marked or disclosed as confidential, (b) all forms and Dosables of financial, traffic, user, and/or other information, (c) any and all details relating to the Assets to be delivered,  including the relevant URL, Vendor or Client’s contact information, and any other information related to the project. This provision is intended to be broadly construed such that all non-public information obtained by a Vendor or Client will be considered Confidential Information.</p>
      <p>Confidential Information will at all times be, and will at all times remain, the property of the providing party and all applicable rights, including, but not limited to, all intellectual property rights, rights of publicity, or other personal or proprietary rights embodied in the Confidential Information will remain in the providing party. Parties agree that it will treat all such Confidential Information as confidential and will not disclose such Confidential Information to any third party; provided, that a Party may disclose the Confidential Information to its Representatives (as defined below) who have a need to know such information in connection with the evaluation of the Assets. A Client shall use at least the same degree of care to avoid disclosure of such Confidential Information as it would use with respect to its own confidential information of like importance.</p>
      <p>The Parties shall not use Confidential Information for any purpose other than to evaluate the project. A Party will prohibit all third-parties that come into possession of the Confidential Information as a result of their access to it from using it for any purpose other than to evaluate the project. The Client is prohibited from using the Confidential Information to circumvent Dosable or its Services in any manner, including, but not limited to, by making direct to Vendor outside of Dosable’s terms, process, or knowledge. The Vendor is strictly prohibited from using the Confidential Information to obtain non-public information from a competitor, to form a competing business, to register domain names pertaining or related to the project, to obtain keyword lists, user lists, or traffic numbers, or to take any other actions by which Client or any other party under Client’s ownership or control uses the Confidential Information for purposes outside of the evaluation of the project.</p>
      <p>In the event that a Vendor is required by law to disclose any Confidential Information, the Client will cooperate with the providing party and, when possible pursuant to statutory or regulatory authority, provide the providing party with prompt, advance written notice so that the providing party may seek a protective order, prevent against the disclosure of Confidential Information, or waive compliance with the provisions of this Agreement.</p>
      <h3>Authority To Bind.</h3>
      <p>Upon execution of this Agreement, the Client acknowledges their acceptance of the terms and conditions contained herein. By executing this Agreement the signatory represents and warrants they have full and unrestricted authority to enter into this Agreement.  If the Client or signatory is entering into this Agreement on behalf of a Dosable, corporation, partnership, or any other entity (collectively, “Entity”), they represent and warrant they have full and unrestricted authority to enter into this on behalf of Entity. In the event the signatory on behalf of Entity does not have full and unrestricted authority to enter into this Agreement, they agree they can be personally jointly and severally liable for any damages incurred by Dosable arising out of, related to or associated with this Agreement, Other Terms of Use and Client’s access to or use of Dosable’s Network including without limitation Services provided to any Vendors through access to or use of the Dosable.</p>
      <h3>Use Of The Services</h3>
      <p>You will not prepare a  replica of our product and/or use, copy, adapt, modify, decompile, reverse engineer, scrape, disassemble, decrypt, attempt to derive the source code, prepare derivative works based upon, distribute, license, sell, rent, transfer, publicly display, publicly perform, transmit, stream, broadcast, or otherwise exploit the Product and Content, except as expressly permitted by Dosable or as permitted under applicable law. Any unauthorized use of the Services is strictly prohibited and will terminate the license granted in these Terms. No licenses or rights are granted to you by implication or otherwise, except for the licenses and rights expressly granted to you.</p>
      <h3>Termination</h3>
      <p>You agree that in the event your listing, posting, or your information violates any provision of these terms, we shall have the right to terminate and/or suspend your membership of the Website and refuse to provide you or any person acting on your behalf access to the Website.</p>
      <h3>Entire Agreement/ Severability</h3>
      <p>These Terms of Service, including all terms and policies referenced herein, contain the entire understanding and supersede all prior agreements between you and Dosable relating to this subject matter and cannot be changed or terminated orally.</p>
      <h3>Assignment</h3>
      <p>You may not assign these Terms or any of the rights granted hereunder without the prior written consent of Dosable, and any attempted assignment without such consent shall be void. Subject to the foregoing restriction, these Terms will be fully binding upon, inure to the benefit of, and be enforceable by us and our respective successors and assigns.</p>
      <h3>Non-waiver</h3>
      <p>Failure by either Dosable or You to exercise or enforce any right conferred shall not be deemed to be a waiver of any such right nor operate so as to bar that exercise or enforcement thereof or of any other right on any later occasion.</p>
      <h3>Indemnification</h3>
      <p>You agree to defend, indemnify, and hold harmless Dosable and its respective employees, contractors, officers, directors, shareholders, agents, representatives, vendors, and content providers from and against any and all liabilities, claims and expenses, including attorneys' fees, that arise from a breach of these Terms of Service for which you are responsible or in connection with your transmission of any content to, on or through our Website. Without limiting your indemnification obligations described herein, we reserve the right to assume the exclusive defense and control of any matter otherwise subject to indemnification by you.</p>
      <h3>Force Majeure</h3>
      <p>Dosable shall not be liable for any delay or failure to perform resulting from causes outside its reasonable control; including, without limitation, any failure to perform hereunder due to unforeseen circumstances or causes beyond its control such as acts of God, pandemic war, terrorism, riots, embargoes, acts of civil or military authorities, fire, floods, accidents, strikes, or shortages of transportation facilities, fuel, energy, labour, or materials.</p>
      <h3>Governing Law And Arbitration</h3>
      <p>The Parties hereby agree that all actions brought in respect of this Agreement, or any Services delivered pursuant to this Agreement, shall be brought before a Competent Court of State of Wyoming, and the parties hereby acknowledge the exclusive jurisdiction of the Competent Courts of State of Wyoming, United States. Therefore, you agree that: Service shall be deemed a passive one that does not give rise to personal jurisdiction over us, either specific or general, in jurisdictions other than State of Wyoming. The application of the United Nations Convention on Contracts for the International Sale of Goods is expressly excluded. You agree to submit to the personal jurisdiction of a competent court located in, State of Wyoming, for any actions for which we retain the right to seek injunctive or other equitable relief in a court of competent jurisdiction to prevent the actual or threatened infringement, misappropriation or violation of our copyrights, trademarks, trade secrets, patents, or other intellectual property or proprietary rights. Parties may opt for arbitration for resolving their dispute.</p>
      <h3>Supplemental terms</h3>
      <p>Specific additional terms are applicable to Physicians using the Dosable platform. In case of any conflict between the supplemental terms outlined in this Section 13 and other terms herein, these additional terms shall take precedence.</p>
      <p>To qualify as a Physician using the website, you must be a licensed physician under contract with or employed by the Medical Practice. Additionally, you are required to agree to adhere to all relevant medical and professional board laws, rules, regulations, and other guidance applicable to you as a Physician in the state(s) where you offer your services. Your relationship with Dosable users, including Dosable patients, is a direct arrangement between you and these individuals. Dosable users do not establish a provider-patient relationship with Dosable. Dosable does not engage in medical practice or provide any medical services. As elaborated below, Physicians are solely responsible for all agreements, consents, notices, and interactions with patients and other consumers. Dosable bears no liability to Physicians for any amounts owed by patients or other consumers.</p>
      <p>Dosable does not offer medical advice, legal advice, or representations concerning any legal or medical issues related to Physicians, their goods, or services. This includes compliance obligations or steps necessary to comply with state or federal laws and regulations.</p>
      <p>Physicians must use the website and provide services in accordance with applicable standards of good medical and professional practice. While software products like the website can enhance the quality of services offered to patients, various factors, including the provider-patient relationship, can impact patient outcomes. Due to intricate technologies and complex decision-making, accurately determining influencing factors and their proportions in an outcome can be challenging or impossible. Physicians are solely responsible for their use of the website and the provision of services.</p>
      <p>Due to complexities and uncertainties in the patient care process, Physicians agree to defend, indemnify, and hold Dosable harmless from any claim brought against Dosable by or on behalf of a patient, a third party, or someone claiming damage due to a familial or financial relationship with a patient. This indemnification applies regardless of the cause, arising from the Physician's use or operation of the website and services. Physicians must obtain Dosable's prior written consent for any settlement or judgment where they acknowledge fault in Dosable or defects in the website or services. Dosable will promptly notify Physicians in writing of any claim subject to this indemnification, provide them with necessary information for defense, and grant exclusive control over defense and settlement.</p>
      <p>As a Physician using the services, you expressly represent that: (i) you are fully licensed and qualified to provide the requested services; (ii) your provision of advice or services complies with all applicable federal and state laws, including patient privacy laws like HIPAA; (iii) you bear full responsibility for the consequences of any advice or information provided through the services; and (iv) your provision of advice or information adheres to professional standards and best practices in your industry.</p>
      <h3>Contact Us</h3>
      <p>If you have any questions or concerns regarding these Terms or our Services, please contact us through the support portal at Contact us or via email at support@dosable.com</p>
    </div>
  </section>
</template>

<script lang="ts" setup>
useHead({
  title: 'Terms of Service'
})
</script>